[package]
name = "rust-gpu"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = "*"
softbuffer = "*"
log = "*"
env_logger = "*"
palette = "*"
glam = "*"
mesh-loader = "*"
